apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: streams-deployment
spec:
  selector:
    matchLabels:
      app: streams
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: streams
    spec:
      containers:
      - name: streams
        image: gzei/streamtest:latest
        env:
        - name: "KAFKA_BROKER_LIST"
          value: "10.43.139.16:19092,10.43.10.91:19092,10.43.2.68:19092,10.43.35.118:19092"
        - name: "INPUT_TOPIC"
          value: "usecase-input3"
        - name: "OUTPUT_TOPIC"
          value: "usecaseOutputTrend3"
