FROM confluentinc/cp-kafka-connect-base:5.3.1
RUN mkdir -p /usr/share/confluent-hub-components/kafka-connect-influx-lenses
ADD kafka-connect-influxdb-1.2.3-2.1.0-all.jar /usr/share/confluent-hub-components/kafka-connect-influx-lenses/
